import os
# Must be set BEFORE importing transformers or gliner
os.environ["HF_HUB_DISABLE_SYMLINKS"] = "1"

import llm_handler
import json
import embedder
import graph_gen
import graph_operator
from datetime import datetime
import time

# --- Configuration ---
DATA_PATH = os.path.join(os.getcwd(), "data", "final_annotated_dataset.json")
OUTPUT_FILE = "ans.json"
CAUSAL_FILE = "causal_chains.json"
LANDING_FILE = "landing_points.json"

# --- Input Data List ---
queries_to_run = [
    {
        "query": "What are the problems faced by customers in flight domain?",
    }
]

follow_up = 0
distance_threshold = 0.6
topK = 20

def load_json_safe(filepath):
    """Helper to load a JSON file if it exists, otherwise return None or empty dict."""
    if os.path.exists(filepath):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return json.load(f)
        except json.JSONDecodeError:
            print(f"Warning: Could not decode {filepath}")
            return None
    return None

def update_master_json(new_entry, filepath):
    """Reads the master file, appends the new entry, and saves it back."""
    data = []
    if os.path.exists(filepath):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
                if not isinstance(data, list):
                    data = []
        except:
            data = []
    
    data.append(new_entry)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4)
    print(f"Saved entry to {filepath}")

# --- Main Execution Loop ---

print("STARTING BATCH PROCESSING-------------------------------------------------------------------")
start_time = datetime.now()
print(f"Start Time: {start_time.time()}")


for i, item in enumerate(queries_to_run):
    curr_query = item["query"]
    try:
        if follow_up == 1 and os.path.exists("conversation_history.json"):
            try:
                with open("conversation_history.json", 'r', encoding='utf-8') as f:
                    history = json.load(f)
                temp_llm = llm_handler.llm()
                print(f"Contextualizing query: '{curr_query}'")
                curr_query = temp_llm.reformat_query(curr_query, history)
                print(f"Reformatted Query: '{curr_query}'")
            except Exception as e:
                print(f"Error during query reformatting: {e}")
                
        # 1. Generate Graphs
        # Note: Assuming generate_json_graph returns something or modifies state. 
        # If it returns the graph object, we capture it, otherwise we just run it.
        pipeline, queries_list = graph_gen.generate_json_graph(
            query=curr_query,
            data_path=DATA_PATH,
            distance_threshold = distance_threshold,
            follow_up=follow_up,
            topK=topK
        )
        
        # 2. Get Answer
        ans, _ = graph_operator.get_ans(curr_query, queries_list, follow_up=follow_up)
        print(f"Answer generated.")

        # 3. Read side-effect files (Causal Chains and Landing Points)
        # These are generated by the modules above, so we read them now.
        causal_data = load_json_safe(CAUSAL_FILE)
        landing_data = load_json_safe(LANDING_FILE)
        candidate_pairs_data=load_json_safe("candidate_pairs.json")
        # 4. Construct the Result Object
        result_entry = {
            "timestamp": datetime.now().isoformat(),
            "query": curr_query,
            "answer": ans,
            "causal_chains_content": causal_data,
            "landing_points_content": landing_data,
            "candidate_pairs_content": candidate_pairs_data
        }

        # 5. Append to Master JSON
        update_master_json(result_entry, OUTPUT_FILE)

    except Exception as e:
        print(f"ERROR processing query '{curr_query}': {e}")
        # Optionally log the error to the json as well
        error_entry = {
            "query": curr_query,
            "error": str(e)
        }
        update_master_json(error_entry, OUTPUT_FILE)

print("-" * 50)
print("BATCH PROCESSING COMPLETE")